@startuml
skinparam {
  classAttributeIconSize 0
  ClassBorderColor Black
  ClassBackgroundColor White
  ClassFontStyle bold
  ClassFontName Courier
  sequenceMessageAlign direction
  ClassAttributeFontName Courier
  ArrowColor Black
  Shadowing false
  'linetype ortho
  'handwritten true
}

hide enum methods

class Fecha {
	- anyo : int
	- mes : int
	- dia : int

	+ toString() : String
	+ esFechaValida() : bool
}

abstract class Clase {
	- hora : Time
	- precio : float
	- duracion : int

	+ toString() : String
	+ calcularPrecio(Alumno) : float
}

abstract class ActividadTaller{
}

Taller "1..n taller" -- "0..n actividades" ActividadTaller

class Trabajo{
    - descripcion : String
}
class Pieza{
    nombre: String
    precio : float
}
class Reparacion{

    + calcularPrecio() : float
}

class Revision{

    + calcularPrecio(): float
}
Reparacion o-->"0..n piezas" Pieza
Reparacion *-->"1..n trabajos" Trabajo
Revision *-->"1..3 trabajos" Trabajo

abstract class ClaseAula{

}

abstract class ClaseCoche{

}

class Teorica{
  + ponerNotas() : bool
  + calcularPrecio(Alumno) : float
}

class Examen{

  + calcularPrecio(Alumno) : float
}

class Practica{

  + calcularPrecio(Alumno) : float
}

class Poligono{

  + calcularPrecio(Alumno) : float
}

class Alumno {
	- carnetAct : String
	- carnetMatr : String
	- descuento : float
    - notas : List<float>

	+ getFechaMatr() : Fecha
    + addNota(float) : Alumno
	+ toString() : String
}

abstract class Persona{
  - nombre : String
  - apellidos : String
  - dni : String
  - telefono : String

}

class Encargado{

}
Encargado --|> Persona

class Profesor{
  - numSS : String
  - salario : float
  - activo : boolean
}

class Coche{
  - catCarn : String
  - matr : String
  - numBast : String
  - marca : String
  - modelo : String

}

class Aula{
  - codigo : String
}

class Autoescuela{
  - codigo : String
  - direccion : String
}

class Taller{
    - nombre : String
    - direccion : String
    - telefono : String
}

Alumno --> Fecha : fechaTeo
Alumno --> Fecha : fechaPrac
Alumno --> Fecha : fechaNac
Alumno --> Fecha : fechaMatr

Profesor --> Fecha : fechaInic
Profesor --> Fecha : fechaFin

Autoescuela "1" --> "1" Encargado
Taller "1" --> "1" Encargado
Clase --> Fecha : fecha

Aula "1 aula" -- "0..n clases" ClaseAula
Coche "1 coche" -- "0..n clases" ClaseCoche
Coche "0..n coches"-- "0..n talleres" Taller

ClaseAula --|> Clase
ClaseCoche --|> Clase
Teorica --|> ClaseAula
Examen --|> ClaseCoche
Practica --|> ClaseCoche
Poligono --|> ClaseCoche
Alumno --|> Persona
Profesor --|> Persona

Alumno "1..n" <--o ClaseAula
Alumno "1..2" <--o ClaseCoche

Autoescuela *--> Aula : aulas
Autoescuela *--> Clase : clases
Autoescuela *--> Alumno : alumnos
Autoescuela *--> Profesor : profesores
Autoescuela *--> Coche : flota

Profesor "1" -- "1..n" Clase

Reparacion --|> ActividadTaller
Revision --|> ActividadTaller

class Contrato {
}
Contrato --> Fecha : fechaInic
Contrato --> Fecha : fechaFin
Contrato "1" --> "1" Autoescuela
Profesor *--> "0..n contratos" Contrato

class Aplicacion{
}

Aplicacion *--> "0..n" Autoescuela
Aplicacion *--> "0..n" Profesor
Aplicacion *--> "0..n" Taller

@enduml
